### ISSUE TITLE
SysExp: Windows 7 support

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [zodiacon/AllTools#1]
It seems that SysExp is for Windows 10 only. Is this by design? Could this be mentioned in some system requirements for the tool?

```
---------------------------
SysExp.exe - Entry Point Not Found
---------------------------
The procedure entry point GetDpiForWindow could not be located in the dynamic link library USER32.dll. 
---------------------------
OK   
---------------------------
```

**Comment by zodiacon** [comment]
I was experimenting with GetDpiForWindow (only available on Win10 version 1809)...
Removing for now to make it work on Win 7.
