### ISSUE TITLE
ProcExpX can not be started on Win10, while building from source is fine

### ISSUE THREAD

**Issue by EthanZBY** [zodiacon/AllTools#2]
Lauched in windbgx with timeline:
: Exception 0xE06D7363 of type CPlusPlus at PC: 0X7FF9B5DDB040
d3d12!D3D12CreateDevice + 0xfe1f   

![image](https://user-images.githubusercontent.com/41062494/94426077-9bd8f380-01bf-11eb-925f-994e133f1209.png)

The source build loads d3d11 instead, which can be started normally.

**Comment by zodiacon** [comment]
Some machines don't support DirectX 12. I've changed the source to use DirectX 11 but forgot to recompile the new version to the AllTools repo.
Will fix

**Comment by EthanZBY** [comment]
I really appreciate your prompt reply, which is not expected. Thanks.

**Comment by EthanZBY** [comment]
Just for your information:

DirectX 12 has been installed, no error found with DxDiag.


00007ff9`730e1de1 488d1598001500     lea     rdx, [d3d12!`string' (00007ff9`73231e80)]
00007ff9`730e1de8 488b0dd9521c00     mov     rcx, qword ptr [d3d12!_imp_D3DKMTQueryAdapterInfo (00007ff9`732a70c8)]
00007ff9`730e1def e804190200         call    d3d12!CallAndLogImpl<long (__cdecl*)(D3DDDI_DESTROYPAGINGQUEUE * __ptr64), D3DDDI_DESTROYPAGINGQUEUE * __ptr64> (00007ff9`731036f8)

0:000> db 00007ff9`73231e80
00007ff9`73231e80  51 41 49 20 28 55 4d 44-52 49 56 45 52 4e 41 4d  QAI (UMDRIVERNAM
00007ff9`73231e90  45 29 00 00 48 4c 4b 00-45 6e 61 62 6c 65 44 72  E)..HLK.EnableDr
00007ff9`73231ea0  69 76 65 72 56 65 72 69-66 69 65 72 00 00 00 00  iverVerifier....
00007ff9`73231eb0  44 65 73 74 72 6f 79 50-61 67 69 6e 67 51 75 65  DestroyPagingQue
00007ff9`73231ec0  75 65 43 42 00 00 00 00-66 6b 4a c5 df 72 e8 4e  ueCB....fkJ..r.N


Please see the exact spot of the error code occurred below:
![image](https://user-images.githubusercontent.com/41062494/94980953-cc72b180-0560-11eb-8186-14e7cf976e00.png)

00007ff9`730e1df8 e8d3b70000         call    d3d12!NDXGI::CUMDAdapter::NTStatusToHResult (00007ff9`730ed5d0)
00007ff9`730e1dfd 8bc8               mov     ecx, eax

0:000> r rax
rax=0000000080070057

**Comment by zodiacon** [comment]
This is really for Dear ImGui as I didn't write this infrastructure code.
